import React, { createContext, useContext, useState, useEffect } from 'react';

export const AVAILABLE_LANGUAGES = [
  { code: 'en', name: 'English', native: 'English', flag: '🇺🇸', region: 'Global / Antarctic Standard' },
  { code: 'es', name: 'Spanish', native: 'Español', flag: '🇪🇸', region: 'España / América Latina' },
  { code: 'fr', name: 'French', native: 'Français', flag: '🇫🇷', region: 'France / Dumont d’Urville' },
  { code: 'de', name: 'German', native: 'Deutsch', flag: '🇩🇪', region: 'Deutschland / Neumayer III' },
  { code: 'ru', name: 'Russian', native: 'Русский', flag: '🇷🇺', region: 'Россия / Станция Восток' },
  { code: 'zh', name: 'Chinese', native: '中文 (简体)', flag: '🇨🇳', region: '中国 / 南极中山站' },
  { code: 'ja', name: 'Japanese', native: '日本語', flag: '🇯🇵', region: '日本 / 昭和基地' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳', region: 'भारत / भारती स्टेशन' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳', region: 'தமிழ்நாடு / இந்தியா' },
  { code: 'ar', name: 'Arabic', native: 'العربية', flag: '🇸🇦', region: 'الشرق الأوسط' },
];

const TRANSLATIONS = {
  en: {
    // Nav
    'nav.dashboard': 'Dashboard',
    'nav.prediction': 'Prediction',
    'nav.optimization': 'Optimization',
    'nav.alerts': 'Alerts & Anomalies',
    'nav.simulation': 'Simulation',
    'nav.reports': 'Reports',
    'nav.data': 'Data Management',
    'nav.settings': 'Settings',
    'nav.operators': 'Operator Management',
    'nav.logout': 'Logout Session',
    'nav.health': 'SYSTEM HEALTH',
    'nav.station': 'Bharati Station',
    'nav.online': 'Online',
    // Header
    'header.title': 'POLAR ENERGY',
    'header.subtitle': 'AUTONOMOUS MICROGRID CONTROL',
    'header.simulation': 'ARCTIC MICROGRID SIMULATION',
    'header.digitalTwin': 'REMOTE ENERGY SYSTEM • LIVE DIGITAL TWIN',
    'header.systemMode': 'SYSTEM MODE',
    'header.autonomous': 'AUTONOMOUS',
    'header.localTime': 'LOCAL TIME',
    'header.admin': 'ADMINISTRATOR',
    'header.operator': 'OPERATOR',
    'header.active': 'Active',
    'header.chooseLanguage': 'Language',
    // Reports
    'reports.title': 'ENERGY ANALYTICS & SIMULATION REPORTS',
    'reports.subtitle': 'Historical generation metrics, simulation outcomes, and fuel audit logs',
    'reports.daily': 'daily',
    'reports.weekly': 'weekly',
    'reports.monthly': 'monthly',
    'reports.exportCsv': 'Export CSV',
    'reports.exporting': 'Exporting...',
    'reports.totalRenewable': 'Total Renewable Generated',
    'reports.zeroCarbon': '100% Zero-Carbon Harvested',
    'reports.renewableFraction': 'Renewable Fraction',
    'reports.target': 'Target: >90% Renewable',
    'reports.dieselConserved': 'Diesel Fuel Conserved',
    'reports.co2Saved': '~1.45 tonnes CO2 equivalent saved',
    'reports.resilienceScore': 'Resilience Score',
    'reports.safeMargin': 'Safe Arctic Operating Margin',
    'reports.tableTitle': 'DIGITAL TWIN SIMULATION RUNS & AUDIT LOG',
    'reports.liveRuns': 'Live Synchronized Runs',
    'reports.colTime': 'Execution Time',
    'reports.colRun': 'Telemetry Run',
    'reports.colRenewable': 'Renewable Share',
    'reports.colLoad': 'Station Load',
    'reports.colDiesel': 'Diesel Used',
    'reports.colStatus': 'Status',
    'reports.chartTitle': 'Energy Generation vs. Station Demand Breakdown (kWh)',
    'reports.chartSubtitle': 'Stacked renewable contribution (Solar + Wind) compared against actual demand.',
    'reports.solarKwh': 'Solar Energy (kWh)',
    'reports.windKwh': 'Wind Energy (kWh)',
    'reports.dieselKwh': 'Diesel Backup (kWh)',
    'reports.loadKwh': 'Station Load Demand (kWh)',
    // Settings
    'settings.title': 'SYSTEM SETTINGS & THRESHOLDS',
    'settings.subtitle': 'Configure polar station telemetry parameters, reserve safety thresholds, ML models, and notification channels.',
    'settings.configurable': 'CONFIGURABLE',
    'settings.saveBtn': 'SAVE SETTINGS',
    'settings.saving': 'PERSISTING TO SQLITE...',
    'settings.saveSuccess': 'System configuration successfully persisted to SQLite database and synchronized with telemetry daemons.',
    'settings.langTitle': 'Language & Regional Preferences',
    'settings.langSubtitle': 'Select interface display language. Updates all navigation, reports, and controls immediately.',
    'settings.stationTitle': 'Station Identification & Telemetry Node',
    'settings.stationName': 'Polar Station Name',
    'settings.location': 'Geographic Coordinates / Location',
    'settings.storageTitle': 'Energy Storage & Generator Thresholds',
    'settings.batteryMinReserve': 'Battery Min Preferred Reserve (%)',
    'settings.batteryFloor': 'Default safety floor: 30%',
    'settings.criticalLoadThreshold': 'Critical Load Surge Threshold (kW)',
    'settings.overloadTrigger': 'Default overload trigger: 55 kW',
    'settings.dieselAutoStart': 'Diesel Generator Auto-Trigger',
    'settings.dieselDeficit': 'Engages diesel if deficit persists',
    'settings.mlTitle': 'Machine Learning Engine Settings',
    'settings.forecastHorizon': 'Forecasting Horizon Window',
    'settings.modelAlgorithm': 'Primary ML Regressor Architecture',
    'settings.alertsTitle': 'Alert Subscriptions & Incident Routing',
    'settings.criticalAlerts': 'Critical Overload & Anomaly Alerts',
    'settings.criticalAlertsDesc': 'Trigger immediate operator alarm upon thermal relay spikes or severe deficit.',
    'settings.warningAlerts': 'Forecasted Shortage Warning Alerts',
    'settings.warningAlertsDesc': 'Notify when 6-hour renewable generation falls below station critical baseline.',
    'settings.systemNotifications': 'System Telemetry Notifications',
    'settings.systemNotificationsDesc': 'Periodic status reports and battery cycle optimization updates.',
  },

  es: {
    'nav.dashboard': 'Panel Principal',
    'nav.prediction': 'Predicción',
    'nav.optimization': 'Optimización',
    'nav.alerts': 'Alertas y Anomalías',
    'nav.simulation': 'Simulación',
    'nav.reports': 'Informes',
    'nav.data': 'Gestión de Datos',
    'nav.settings': 'Configuración',
    'nav.operators': 'Gestión de Operadores',
    'nav.logout': 'Cerrar Sesión',
    'nav.health': 'SALUD DEL SISTEMA',
    'nav.station': 'Estación Bharati',
    'nav.online': 'En Línea',
    'header.title': 'ENERGÍA POLAR',
    'header.subtitle': 'CONTROL AUTÓNOMO DE MICRORED',
    'header.simulation': 'SIMULACIÓN DE MICRORED ÁRTICA',
    'header.digitalTwin': 'SISTEMA DE ENERGÍA REMOTO • GEMELO DIGITAL EN VIVO',
    'header.systemMode': 'MODO DEL SISTEMA',
    'header.autonomous': 'AUTÓNOMO',
    'header.localTime': 'HORA LOCAL',
    'header.admin': 'ADMINISTRADOR',
    'header.operator': 'OPERADOR',
    'header.active': 'Activo',
    'header.chooseLanguage': 'Idioma',
    'reports.title': 'ANÁLISIS DE ENERGÍA E INFORMES DE SIMULACIÓN',
    'reports.subtitle': 'Métricas de generación histórica, resultados de simulación y registros de combustible',
    'reports.daily': 'diario',
    'reports.weekly': 'semanal',
    'reports.monthly': 'mensual',
    'reports.exportCsv': 'Exportar CSV',
    'reports.exporting': 'Exportando...',
    'reports.totalRenewable': 'Total Renovable Generado',
    'reports.zeroCarbon': '100% Libre de Carbono',
    'reports.renewableFraction': 'Fracción Renovable',
    'reports.target': 'Objetivo: >90% Renovable',
    'reports.dieselConserved': 'Combustible Diésel Ahorrado',
    'reports.co2Saved': '~1.45 toneladas CO2 equivalente ahorrado',
    'reports.resilienceScore': 'Puntuación de Resiliencia',
    'reports.safeMargin': 'Margen Operativo Ártico Seguro',
    'reports.tableTitle': 'EJECUCIONES DE SIMULACIÓN Y REGISTRO DE AUDITORÍA',
    'reports.liveRuns': 'Ejecuciones Sincronizadas en Vivo',
    'reports.colTime': 'Hora de Ejecución',
    'reports.colRun': 'Ejecución de Telemetría',
    'reports.colRenewable': 'Cuota Renovable',
    'reports.colLoad': 'Carga de la Estación',
    'reports.colDiesel': 'Diésel Utilizado',
    'reports.colStatus': 'Estado',
    'reports.chartTitle': 'Generación de Energía vs. Demanda de la Estación (kWh)',
    'reports.chartSubtitle': 'Contribución renovable apilada (Solar + Eólica) frente a la demanda real.',
    'reports.solarKwh': 'Energía Solar (kWh)',
    'reports.windKwh': 'Energía Eólica (kWh)',
    'reports.dieselKwh': 'Respaldo Diésel (kWh)',
    'reports.loadKwh': 'Demanda de Carga (kWh)',
    'settings.title': 'AJUSTES DEL SISTEMA Y UMBRALES',
    'settings.subtitle': 'Configurar parámetros de telemetría, umbrales de reserva, modelos de ML y canales de notificación.',
    'settings.configurable': 'CONFIGURABLE',
    'settings.saveBtn': 'GUARDAR AJUSTES',
    'settings.saving': 'GUARDANDO EN SQLITE...',
    'settings.saveSuccess': 'Configuración del sistema guardada con éxito en la base de datos SQLite.',
    'settings.langTitle': 'Preferencias de Idioma y Región',
    'settings.langSubtitle': 'Seleccione el idioma de la interfaz. Actualiza la navegación, informes y controles.',
    'settings.stationTitle': 'Identificación de la Estación y Nodo',
    'settings.stationName': 'Nombre de la Estación Polar',
    'settings.location': 'Coordenadas Geográficas / Ubicación',
    'settings.storageTitle': 'Almacenamiento de Energía y Generadores',
    'settings.batteryMinReserve': 'Reserva Mínima Preferida de Batería (%)',
    'settings.batteryFloor': 'Límite de seguridad predeterminado: 30%',
    'settings.criticalLoadThreshold': 'Umbral Crítico de Carga (kW)',
    'settings.overloadTrigger': 'Disparador de sobrecarga: 55 kW',
    'settings.dieselAutoStart': 'Auto-activación del Generador Diésel',
    'settings.dieselDeficit': 'Activa el diésel si el déficit persiste',
    'settings.mlTitle': 'Configuración del Motor de Machine Learning',
    'settings.forecastHorizon': 'Ventana de Pronóstico',
    'settings.modelAlgorithm': 'Arquitectura de Regresión ML',
    'settings.alertsTitle': 'Suscripciones a Alertas y Notificaciones',
    'settings.criticalAlerts': 'Alertas Críticas de Sobrecarga y Anomalías',
    'settings.criticalAlertsDesc': 'Activa alarma inmediata del operador ante picos térmicos o déficit severo.',
    'settings.warningAlerts': 'Alertas de Escasez Prevista',
    'settings.warningAlertsDesc': 'Notifica cuando la generación cae por debajo del umbral crítico.',
    'settings.systemNotifications': 'Notificaciones del Sistema',
    'settings.systemNotificationsDesc': 'Informes periódicos y optimización de ciclos de batería.',
  },

  fr: {
    'nav.dashboard': 'Tableau de bord',
    'nav.prediction': 'Prévision',
    'nav.optimization': 'Optimisation',
    'nav.alerts': 'Alertes et Anomalies',
    'nav.simulation': 'Simulation',
    'nav.reports': 'Rapports',
    'nav.data': 'Gestion des Données',
    'nav.settings': 'Paramètres',
    'nav.operators': 'Gestion des Opérateurs',
    'nav.logout': 'Déconnexion',
    'nav.health': 'SANTÉ DU SYSTÈME',
    'nav.station': 'Station Bharati',
    'nav.online': 'En Ligne',
    'header.title': 'ÉNERGIE POLAIRE',
    'header.subtitle': 'CONTRÔLE AUTONOME DE MICRO-RÉSEAU',
    'header.simulation': 'SIMULATION DE MICRO-RÉSEAU ARCTIQUE',
    'header.digitalTwin': 'SYSTÈME ÉNERGÉTIQUE DISTANT • JUMEAU NUMÉRIQUE',
    'header.systemMode': 'MODE SYSTÈME',
    'header.autonomous': 'AUTONOME',
    'header.localTime': 'HEURE LOCALE',
    'header.admin': 'ADMINISTRATEUR',
    'header.operator': 'OPÉRATEUR',
    'header.active': 'Actif',
    'header.chooseLanguage': 'Langue',
    'reports.title': 'ANALYTIQUE ÉNERGÉTIQUE & RAPPORTS DE SIMULATION',
    'reports.subtitle': 'Mesures historiques de production, résultats de simulation et audits de carburant',
    'reports.daily': 'quotidien',
    'reports.weekly': 'hebdomadaire',
    'reports.monthly': 'mensuel',
    'reports.exportCsv': 'Exporter CSV',
    'reports.exporting': 'Exportation...',
    'reports.totalRenewable': 'Total Renouvelable Produit',
    'reports.zeroCarbon': '100% Zéro-Carbone Collecté',
    'reports.renewableFraction': 'Part Renouvelable',
    'reports.target': 'Objectif : >90% Renouvelable',
    'reports.dieselConserved': 'Carburant Diesel Économisé',
    'reports.co2Saved': '~1.45 tonnes de CO2 économisées',
    'reports.resilienceScore': 'Score de Résilience',
    'reports.safeMargin': 'Marge de Sécurité Arctique',
    'reports.tableTitle': 'RUNS DE SIMULATION ET JOURNAL D’AUDIT',
    'reports.liveRuns': 'Runs Synchronisés en Direct',
    'reports.colTime': 'Heure d’Exécution',
    'reports.colRun': 'Run Télémétrie',
    'reports.colRenewable': 'Part Renouvelable',
    'reports.colLoad': 'Charge Station',
    'reports.colDiesel': 'Diesel Consommé',
    'reports.colStatus': 'Statut',
    'reports.chartTitle': 'Production d’Énergie vs. Demande de la Station (kWh)',
    'reports.chartSubtitle': 'Contribution renouvelable cumulée (Solaire + Éolien) comparée à la demande réelle.',
    'reports.solarKwh': 'Énergie Solaire (kWh)',
    'reports.windKwh': 'Énergie Éolienne (kWh)',
    'reports.dieselKwh': 'Secours Diesel (kWh)',
    'reports.loadKwh': 'Demande de Charge (kWh)',
    'settings.title': 'PARAMÈTRES SYSTÈME & SEUILS',
    'settings.subtitle': 'Configurer les paramètres de télémétrie, seuils de réserve, modèles IA et alertes.',
    'settings.configurable': 'CONFIGURABLE',
    'settings.saveBtn': 'ENREGISTRER LES PARAMÈTRES',
    'settings.saving': 'ENREGISTREMENT SQLITE...',
    'settings.saveSuccess': 'Configuration enregistrée avec succès dans la base de données SQLite.',
    'settings.langTitle': 'Langue et Préférences Régionales',
    'settings.langSubtitle': 'Sélectionnez la langue d’affichage de l’interface.',
    'settings.stationTitle': 'Identification de la Station',
    'settings.stationName': 'Nom de la Station Polaire',
    'settings.location': 'Coordonnées Géographiques / Localisation',
    'settings.storageTitle': 'Stockage d’Énergie & Générateurs',
    'settings.batteryMinReserve': 'Réserve Minimale de Batterie (%)',
    'settings.batteryFloor': 'Seuil de sécurité par défaut : 30%',
    'settings.criticalLoadThreshold': 'Seuil de Charge Critique (kW)',
    'settings.overloadTrigger': 'Déclencheur de surcharge : 55 kW',
    'settings.dieselAutoStart': 'Démarrage Automatique du Diesel',
    'settings.dieselDeficit': 'Active le diesel en cas de déficit persistant',
    'settings.mlTitle': 'Paramètres du Moteur Machine Learning',
    'settings.forecastHorizon': 'Horizon de Prévision',
    'settings.modelAlgorithm': 'Algorithme de Régression ML',
    'settings.alertsTitle': 'Abonnements aux Alertes',
    'settings.criticalAlerts': 'Alertes de Surcharge Critique & Anomalies',
    'settings.criticalAlertsDesc': 'Alarme immédiate en cas de pic thermique ou déficit sévère.',
    'settings.warningAlerts': 'Alertes de Pénurie Prévisionnelle',
    'settings.warningAlertsDesc': 'Notifie si la production tombe sous le seuil critique.',
    'settings.systemNotifications': 'Notifications Télémétriques',
    'settings.systemNotificationsDesc': 'Rapports périodiques et optimisation des cycles de batterie.',
  },

  de: {
    'nav.dashboard': 'Dashboard',
    'nav.prediction': 'Vorhersage',
    'nav.optimization': 'Optimierung',
    'nav.alerts': 'Warnungen & Anomalien',
    'nav.simulation': 'Simulation',
    'nav.reports': 'Berichte',
    'nav.data': 'Datenverwaltung',
    'nav.settings': 'Einstellungen',
    'nav.operators': 'Bedienerverwaltung',
    'nav.logout': 'Abmelden',
    'nav.health': 'SYSTEMSTATUS',
    'nav.station': 'Bharati Station',
    'nav.online': 'Online',
    'header.title': 'POLAR ENERGY',
    'header.subtitle': 'AUTONOMES MIKRONETZ-STEUERUNGSSYSTEM',
    'header.simulation': 'ARKTISCHE MIKRONETZ-SIMULATION',
    'header.digitalTwin': 'ENTLEGENES ENERGIESYSTEM • DIGITALER ZWILLING',
    'header.systemMode': 'SYSTEMMODUS',
    'header.autonomous': 'AUTONOM',
    'header.localTime': 'LOKALZEIT',
    'header.admin': 'ADMINISTRATOR',
    'header.operator': 'OPERATOR',
    'header.active': 'Aktiv',
    'header.chooseLanguage': 'Sprache',
    'reports.title': 'ENERGIEANALYTIK & SIMULATIONSBERICHTE',
    'reports.subtitle': 'Historische Erzeugungskennzahlen, Simulationsergebnisse und Kraftstoffprotokolle',
    'reports.daily': 'täglich',
    'reports.weekly': 'wöchentlich',
    'reports.monthly': 'monatlich',
    'reports.exportCsv': 'CSV Exportieren',
    'reports.exporting': 'Exportiert...',
    'reports.totalRenewable': 'Gesamte Erneuerbare Erzeugung',
    'reports.zeroCarbon': '100% Null-Kohlenstoff Geerntet',
    'reports.renewableFraction': 'Erneuerbarer Anteil',
    'reports.target': 'Ziel: >90% Erneuerbar',
    'reports.dieselConserved': 'Eingesparter Dieselkraftstoff',
    'reports.co2Saved': '~1.45 Tonnen CO2-Äquivalent gespart',
    'reports.resilienceScore': 'Resilienz-Bewertung',
    'reports.safeMargin': 'Sichere Arktische Betriebsspanne',
    'reports.tableTitle': 'SIMULATIONSLÄUFE & AUDIT-PROTOKOLL',
    'reports.liveRuns': 'Live Synchronisierte Läufe',
    'reports.colTime': 'Ausführungszeit',
    'reports.colRun': 'Telemetrie-Lauf',
    'reports.colRenewable': 'Erneuerbarer Anteil',
    'reports.colLoad': 'Stationslast',
    'reports.colDiesel': 'Diesel Verbraucht',
    'reports.colStatus': 'Status',
    'reports.chartTitle': 'Energieerzeugung vs. Stationsbedarf (kWh)',
    'reports.chartSubtitle': 'Gestapelter erneuerbarer Beitrag (Solar + Wind) im Vergleich zur tatsächlichen Last.',
    'reports.solarKwh': 'Solarenergie (kWh)',
    'reports.windKwh': 'Windenergie (kWh)',
    'reports.dieselKwh': 'Diesel-Reserve (kWh)',
    'reports.loadKwh': 'Stations-Lastbedarf (kWh)',
    'settings.title': 'SYSTEMEINSTELLUNGEN & SCHWELLENWERTE',
    'settings.subtitle': 'Polarstation-Telemetrieparameter, Reservesicherheitsgrenzen und ML-Modelle anpassen.',
    'settings.configurable': 'KONFIGURIERBAR',
    'settings.saveBtn': 'EINSTELLUNGEN SPEICHERN',
    'settings.saving': 'SPEICHERT IN SQLITE...',
    'settings.saveSuccess': 'Systemkonfiguration erfolgreich in SQLite-Datenbank gespeichert.',
    'settings.langTitle': 'Sprach- und Regionaleinstellungen',
    'settings.langSubtitle': 'Wählen Sie die Sprache der Benutzeroberfläche aus.',
    'settings.stationTitle': 'Stationsidentifikation & Telemetrieknoten',
    'settings.stationName': 'Name der Polarstation',
    'settings.location': 'Geografische Koordinaten / Standort',
    'settings.storageTitle': 'Energiespeicher & Generator-Schwellen',
    'settings.batteryMinReserve': 'Mindest-Batteriereserve (%)',
    'settings.batteryFloor': 'Standardsicherheitsgrenze: 30%',
    'settings.criticalLoadThreshold': 'Kritische Lastüberlastungsschwelle (kW)',
    'settings.overloadTrigger': 'Standard-Überlastungsauslöser: 55 kW',
    'settings.dieselAutoStart': 'Diesel-Generator Autostart',
    'settings.dieselDeficit': 'Startet Diesel bei anhaltendem Defizit',
    'settings.mlTitle': 'Machine Learning Engine Einstellungen',
    'settings.forecastHorizon': 'Prognose-Zeithorizont',
    'settings.modelAlgorithm': 'Primäre ML-Regressor-Architektur',
    'settings.alertsTitle': 'Warnungsabonnements & Routing',
    'settings.criticalAlerts': 'Kritische Überlast- & Anomaliewarnungen',
    'settings.criticalAlertsDesc': 'Sofortiger Alarm bei thermischen Spitzen oder schwerem Defizit.',
    'settings.warningAlerts': 'Prognostizierte Knappheitswarnungen',
    'settings.warningAlertsDesc': 'Benachrichtigung wenn 6-Stunden-Erzeugung unter Basislinie fällt.',
    'settings.systemNotifications': 'System-Telemetrie-Benachrichtigungen',
    'settings.systemNotificationsDesc': 'Regelmäßige Statusberichte und Batterieoptimierung.',
  },

  ru: {
    'nav.dashboard': 'Панель Управления',
    'nav.prediction': 'Прогнозирование',
    'nav.optimization': 'Оптимизация',
    'nav.alerts': 'Оповещения и Аномалии',
    'nav.simulation': 'Симуляция',
    'nav.reports': 'Отчеты',
    'nav.data': 'Управление Данными',
    'nav.settings': 'Настройки',
    'nav.operators': 'Управление Операторами',
    'nav.logout': 'Выйти из Системы',
    'nav.health': 'СОСТОЯНИЕ СИСТЕМЫ',
    'nav.station': 'Станция Бхарати',
    'nav.online': 'В Сети',
    'header.title': 'ПОЛЯРНАЯ ЭНЕРГИЯ',
    'header.subtitle': 'АВТОНОМНОЕ УПРАВЛЕНИЕ МИКРОСЕТЬЮ',
    'header.simulation': 'АРКТИЧЕСКАЯ СИМУЛЯЦИЯ МИКРОСЕТИ',
    'header.digitalTwin': 'УДАЛЕННАЯ ЭНЕРГОСИСТЕМА • ЦИФРОВОЙ ДВОЙНИК',
    'header.systemMode': 'РЕЖИМ СИСТЕМЫ',
    'header.autonomous': 'АВТОНОМНЫЙ',
    'header.localTime': 'МЕСТНОЕ ВРЕМЯ',
    'header.admin': 'АДМИНИСТРАТОР',
    'header.operator': 'ОПЕРАТОР',
    'header.active': 'Активен',
    'header.chooseLanguage': 'Язык',
    'reports.title': 'АНАЛИТИКА ЭНЕРГИИ И ОТЧЕТЫ СИМУЛЯЦИИ',
    'reports.subtitle': 'Исторические показатели генерации, результаты моделирования и аудит топлива',
    'reports.daily': 'по дням',
    'reports.weekly': 'недельный',
    'reports.monthly': 'месячный',
    'reports.exportCsv': 'Экспорт CSV',
    'reports.exporting': 'Экспорт...',
    'reports.totalRenewable': 'Всего Возобновляемой Генерации',
    'reports.zeroCarbon': '100% Безуглеродная Энергия',
    'reports.renewableFraction': 'Доля Возобновляемой Энергии',
    'reports.target': 'Цель: >90% Возобновляемая',
    'reports.dieselConserved': 'Сэкономлено Дизельного Топлива',
    'reports.co2Saved': '~1.45 тонн CO2 сэкономлено',
    'reports.resilienceScore': 'Индекс Устойчивости',
    'reports.safeMargin': 'Безопасный Арктический Запас',
    'reports.tableTitle': 'СИМУЛЯЦИОННЫЕ ПРОГОНЫ И ЖУРНАЛ АУДИТА',
    'reports.liveRuns': 'Синхронизированные Прогоны',
    'reports.colTime': 'Время Выполнения',
    'reports.colRun': 'Прогон Телеметрии',
    'reports.colRenewable': 'Доля ВИЭ',
    'reports.colLoad': 'Нагрузка Станции',
    'reports.colDiesel': 'Дизель (л)',
    'reports.colStatus': 'Статус',
    'reports.chartTitle': 'Генерация Энергии vs. Потребление Станции (кВт·ч)',
    'reports.chartSubtitle': 'Суммарный вклад ВИЭ (Солнце + Ветер) против фактического спроса.',
    'reports.solarKwh': 'Солнечная Энергия (кВт·ч)',
    'reports.windKwh': 'Ветровая Энергия (кВт·ч)',
    'reports.dieselKwh': 'Дизельный Резерв (кВт·ч)',
    'reports.loadKwh': 'Спрос Нагрузки (кВт·ч)',
    'settings.title': 'СИСТЕМНЫЕ НАСТРОЙКИ И ПОРОГИ',
    'settings.subtitle': 'Настройка параметров телеметрии, порогов резервирования и моделей МО.',
    'settings.configurable': 'НАСТРАИВАЕМЫЙ',
    'settings.saveBtn': 'СОХРАНИТЬ НАСТРОЙКИ',
    'settings.saving': 'СОХРАНЕНИЕ В SQLITE...',
    'settings.saveSuccess': 'Конфигурация системы успешно сохранена в базе данных SQLite.',
    'settings.langTitle': 'Языковые и Региональные Настройки',
    'settings.langSubtitle': 'Выберите язык интерфейса. Мгновенно обновляет все разделы.',
    'settings.stationTitle': 'Идентификация Станции и Узел Телеметрии',
    'settings.stationName': 'Название Полярной Станции',
    'settings.location': 'Географические Координаты / Локация',
    'settings.storageTitle': 'Накопители Энергии и Генераторы',
    'settings.batteryMinReserve': 'Мин. Резерв Батареи (%)',
    'settings.batteryFloor': 'Порог безопасности: 30%',
    'settings.criticalLoadThreshold': 'Порог Критической Перегрузки (кВт)',
    'settings.overloadTrigger': 'Триггер перегрузки: 55 кВт',
    'settings.dieselAutoStart': 'Автозапуск Дизель-Генератора',
    'settings.dieselDeficit': 'Запуск дизеля при сохранении дефицита',
    'settings.mlTitle': 'Параметры Движка Машинного Обучения',
    'settings.forecastHorizon': 'Горизонт Прогнозирования',
    'settings.modelAlgorithm': 'Архитектура ML Регрессора',
    'settings.alertsTitle': 'Маршрутизация Оповещений',
    'settings.criticalAlerts': 'Критические Оповещения о Перегрузке',
    'settings.criticalAlertsDesc': 'Немедленная тревога при тепловых скачках или остром дефиците.',
    'settings.warningAlerts': 'Предупреждения о Дефиците',
    'settings.warningAlertsDesc': 'Уведомление при падении выработки ниже базовой линии.',
    'settings.systemNotifications': 'Системные Телеметрические Уведомления',
    'settings.systemNotificationsDesc': 'Периодические отчеты о состоянии и оптимизации аккумуляторов.',
  },

  zh: {
    'nav.dashboard': '仪表板',
    'nav.prediction': '负荷预测',
    'nav.optimization': '智能调度优化',
    'nav.alerts': '警报与异常',
    'nav.simulation': '数字孪生仿真',
    'nav.reports': '能效分析报告',
    'nav.data': '数据管理中心',
    'nav.settings': '系统配置',
    'nav.operators': '操作员权限管理',
    'nav.logout': '安全退出',
    'nav.health': '系统健康状态',
    'nav.station': '巴蒂极地站',
    'nav.online': '在线运行',
    'header.title': '极地智能微电网',
    'header.subtitle': '自主微电网控制系统',
    'header.simulation': '极地微电网仿真中心',
    'header.digitalTwin': '远程能源系统 • 实时数字孪生',
    'header.systemMode': '运行模式',
    'header.autonomous': '全自主控制',
    'header.localTime': '当地时间',
    'header.admin': '系统管理员',
    'header.operator': '电站操作员',
    'header.active': '正常活跃',
    'header.chooseLanguage': '界面语言',
    'reports.title': '能源分析与仿真运行报告',
    'reports.subtitle': '历史发电指标、仿真推演结果与柴油节约审计日志',
    'reports.daily': '按日分析',
    'reports.weekly': '按周统计',
    'reports.monthly': '按月汇总',
    'reports.exportCsv': '导出 CSV 报表',
    'reports.exporting': '正在导出...',
    'reports.totalRenewable': '可再生能源总发电量',
    'reports.zeroCarbon': '100% 零碳绿电捕获',
    'reports.renewableFraction': '可再生能源占比',
    'reports.target': '考核目标: >90% 绿电',
    'reports.dieselConserved': '节约柴油燃料总量',
    'reports.co2Saved': '等效减排 ~1.45 吨二氧化碳',
    'reports.resilienceScore': '极地电网韧性评分',
    'reports.safeMargin': '极地严寒安全冗余区间',
    'reports.tableTitle': '数字孪生仿真执行记录与审计台账',
    'reports.liveRuns': '实时同步仿真流',
    'reports.colTime': '执行时间',
    'reports.colRun': '遥测推演任务',
    'reports.colRenewable': '绿电占比',
    'reports.colLoad': '站区实时负荷',
    'reports.colDiesel': '柴油消耗量',
    'reports.colStatus': '运行状态',
    'reports.chartTitle': '能源生成 vs. 站区用电负荷对比 (kWh)',
    'reports.chartSubtitle': '风光互补发电叠加贡献与实际负荷需求对比',
    'reports.solarKwh': '光伏发电 (kWh)',
    'reports.windKwh': '风力发电 (kWh)',
    'reports.dieselKwh': '柴油应急后备 (kWh)',
    'reports.loadKwh': '站区负荷需求 (kWh)',
    'settings.title': '系统参数与安全阈值设置',
    'settings.subtitle': '配置极地站遥测参数、储能安全冗余底线、机器学习模型及预警通知通道。',
    'settings.configurable': '支持动态配置',
    'settings.saveBtn': '保存配置参数',
    'settings.saving': '正在写入 SQLite 数据库...',
    'settings.saveSuccess': '系统配置已成功持久化至 SQLite 数据库并同步至遥测守护进程。',
    'settings.langTitle': '多语言与区域设置',
    'settings.langSubtitle': '选择界面显示语言。即时更新导航、报表和各功能模块。',
    'settings.stationTitle': '站点标识与遥测节点',
    'settings.stationName': '极地考察站名称',
    'settings.location': '地理经纬度坐标 / 站点位置',
    'settings.storageTitle': '储能电池与发电机保护阈值',
    'settings.batteryMinReserve': '储能电池最低安全保留容量 (%)',
    'settings.batteryFloor': '默认安全底线: 30%',
    'settings.criticalLoadThreshold': '关键负荷突增告警阈值 (kW)',
    'settings.overloadTrigger': '过载保护触发值: 55 kW',
    'settings.dieselAutoStart': '应急柴油发电机自启动阈值',
    'settings.dieselDeficit': '在可再生能源赤字持续时自动投切',
    'settings.mlTitle': '机器学习与预测引擎配置',
    'settings.forecastHorizon': '未来预测时间窗口',
    'settings.modelAlgorithm': '主回归预测算法架构',
    'settings.alertsTitle': '告警订阅与事件路由通道',
    'settings.criticalAlerts': '严重过载与电气异常告警',
    'settings.criticalAlertsDesc': '当热敏继电器过载或出现严重缺额时立即触发蜂鸣器。',
    'settings.warningAlerts': '新能源短缺前瞻预警',
    'settings.warningAlertsDesc': '当未来6小时绿电生成低于关键底线时推送预警。',
    'settings.systemNotifications': '系统遥测与调度通知',
    'settings.systemNotificationsDesc': '定期发送电站健康状态简报与电池充放电周期优化建议。',
  },

  ja: {
    'nav.dashboard': 'ダッシュボード',
    'nav.prediction': '予測分析',
    'nav.optimization': '最適化制御',
    'nav.alerts': '警報と異常検知',
    'nav.simulation': 'シミュレーション',
    'nav.reports': 'レポート',
    'nav.data': 'データ管理',
    'nav.settings': 'システム設定',
    'nav.operators': '運用者管理',
    'nav.logout': 'ログアウト',
    'nav.health': 'システム健全性',
    'nav.station': 'バルティ基地',
    'nav.online': '稼働中',
    'header.title': '極地エネルギーAI',
    'header.subtitle': '自律型マイクログリッド制御',
    'header.simulation': '極地マイクログリッドシミュレーション',
    'header.digitalTwin': '遠隔エネルギー基盤 • リアルタイムデジタルツイン',
    'header.systemMode': '運用モード',
    'header.autonomous': '完全自律',
    'header.localTime': '現地時刻',
    'header.admin': '管理者',
    'header.operator': '運用担当者',
    'header.active': '有効',
    'header.chooseLanguage': '言語設定',
    'reports.title': 'エネルギー分析 & シミュレーションレポート',
    'reports.subtitle': '過去の発電実績、シミュレーション結果、燃料監査ログ',
    'reports.daily': '日間',
    'reports.weekly': '週間',
    'reports.monthly': '月間',
    'reports.exportCsv': 'CSVエクスポート',
    'reports.exporting': '出力中...',
    'reports.totalRenewable': '総再エネ発電量',
    'reports.zeroCarbon': '100% ゼロカーボン発電',
    'reports.renewableFraction': '再生可能エネルギー比率',
    'reports.target': '目標: >90% 再エネ',
    'reports.dieselConserved': '削減ディーゼル燃料',
    'reports.co2Saved': '約1.45トンのCO2削減相当',
    'reports.resilienceScore': 'レジリエンススコア',
    'reports.safeMargin': '極地安全マージン',
    'reports.tableTitle': 'デジタルツイン実行履歴 & 監査ログ',
    'reports.liveRuns': 'リアルタイム同期実行',
    'reports.colTime': '実行時刻',
    'reports.colRun': 'テレメトリ実行',
    'reports.colRenewable': '再エネ率',
    'reports.colLoad': '基地負荷',
    'reports.colDiesel': 'ディーゼル使用量',
    'reports.colStatus': '状態',
    'reports.chartTitle': '発電量 vs. 基地電力需要内訳 (kWh)',
    'reports.chartSubtitle': '再エネ（太陽光＋風力）発電と実際の消費需要の比較',
    'reports.solarKwh': '太陽光発電 (kWh)',
    'reports.windKwh': '風力発電 (kWh)',
    'reports.dieselKwh': 'ディーゼル補完 (kWh)',
    'reports.loadKwh': '電力需要 (kWh)',
    'settings.title': 'システム設定 & しきい値管理',
    'settings.subtitle': '基地テレメトリ、蓄電池安全基準、MLモデル、通知の設定。',
    'settings.configurable': '設定可能',
    'settings.saveBtn': '設定を保存',
    'settings.saving': 'SQLiteに保存中...',
    'settings.saveSuccess': '設定がSQLiteデータベースに正常に保存されました。',
    'settings.langTitle': '言語および地域設定',
    'settings.langSubtitle': '表示言語を選択します。すべての画面に即座に反映されます。',
    'settings.stationTitle': '基地識別情報 & テレメトリノード',
    'settings.stationName': '極地観測基地名',
    'settings.location': '地理座標 / 所在地',
    'settings.storageTitle': '蓄電システム & 発電機しきい値',
    'settings.batteryMinReserve': '蓄電池最低維持容量 (%)',
    'settings.batteryFloor': '安全基準下限: 30%',
    'settings.criticalLoadThreshold': '重大負荷サージしきい値 (kW)',
    'settings.overloadTrigger': '過負荷基準値: 55 kW',
    'settings.dieselAutoStart': 'ディーゼル発電機自動起動',
    'settings.dieselDeficit': '電力不足継続時に自動投入',
    'settings.mlTitle': '機械学習エンジン設定',
    'settings.forecastHorizon': '予測時間枠',
    'settings.modelAlgorithm': '回帰アルゴリズム',
    'settings.alertsTitle': 'アラート通知設定',
    'settings.criticalAlerts': '重大過負荷 & 異常検知アラート',
    'settings.criticalAlertsDesc': '熱過負荷や電力不足時に即時オペレータに通知。',
    'settings.warningAlerts': '発電不足予測アラート',
    'settings.warningAlertsDesc': '6時間以内の発電量低下を事前通知。',
    'settings.systemNotifications': 'システム状態通知',
    'settings.systemNotificationsDesc': '定期レポートおよび蓄電池最適化情報。',
  },

  hi: {
    'nav.dashboard': 'डैशबोर्ड',
    'nav.prediction': 'पूर्वानुमान',
    'nav.optimization': 'अनुकूलन',
    'nav.alerts': 'अलर्ट और विसंगतियां',
    'nav.simulation': 'सिमुलेशन',
    'nav.reports': 'रिपोर्ट्स',
    'nav.data': 'डेटा प्रबंधन',
    'nav.settings': 'सेटिंग्स',
    'nav.operators': 'ऑपरेटर प्रबंधन',
    'nav.logout': 'लॉगआउट',
    'nav.health': 'सिस्टम स्वास्थ्य',
    'nav.station': 'भारती स्टेशन',
    'nav.online': 'ऑनलाइन',
    'header.title': 'पोलर एनर्जी एआई',
    'header.subtitle': 'स्वायत्त माइक्रोग्रिड नियंत्रण',
    'header.simulation': 'आर्कटिक माइक्रोग्रिड सिमुलेशन',
    'header.digitalTwin': 'दूरस्थ ऊर्जा प्रणाली • लाइव डिजिटल ट्विन',
    'header.systemMode': 'सिस्टम मोड',
    'header.autonomous': 'स्वायत्त',
    'header.localTime': 'स्थानीय समय',
    'header.admin': 'व्यवस्थापक',
    'header.operator': 'ऑपरेटर',
    'header.active': 'सक्रिय',
    'header.chooseLanguage': 'भाषा',
    'reports.title': 'ऊर्जा विश्लेषण एवं सिमुलेशन रिपोर्ट्स',
    'reports.subtitle': 'ऐतिहासिक उत्पादन मेट्रिक्स, सिमुलेशन परिणाम और ईंधन ऑडिट लॉग',
    'reports.daily': 'दैनिक',
    'reports.weekly': 'साप्ताहिक',
    'reports.monthly': 'मासिक',
    'reports.exportCsv': 'CSV निर्यात करें',
    'reports.exporting': 'निर्यात हो रहा है...',
    'reports.totalRenewable': 'कुल नवीकरणीय उत्पादन',
    'reports.zeroCarbon': '100% शून्य-कार्बन ऊर्जा',
    'reports.renewableFraction': 'नवीकरणीय अंश',
    'reports.target': 'लक्ष्य: >90% नवीकरणीय',
    'reports.dieselConserved': 'बचाया गया डीजल ईंधन',
    'reports.co2Saved': '~1.45 टन CO2 समकक्ष बचत',
    'reports.resilienceScore': 'लचीलापन स्कोर',
    'reports.safeMargin': 'सुरक्षित ध्रुवीय संचालन मार्जिन',
    'reports.tableTitle': 'डिजिटल ट्विन सिमुलेशन रन और ऑडिट लॉग',
    'reports.liveRuns': 'लाइव सिंक्रनाइज़ किए गए रन',
    'reports.colTime': 'निष्पादन समय',
    'reports.colRun': 'टेलीमेट्री रन',
    'reports.colRenewable': 'नवीकरणीय हिस्सा',
    'reports.colLoad': 'स्टेशन लोड',
    'reports.colDiesel': 'डीजल का उपयोग',
    'reports.colStatus': 'स्थिति',
    'reports.chartTitle': 'ऊर्जा उत्पादन बनाम स्टेशन मांग विवरण (kWh)',
    'reports.chartSubtitle': 'वास्तविक मांग की तुलना में संचित नवीकरणीय योगदान (सौर + पवन)।',
    'reports.solarKwh': 'सौर ऊर्जा (kWh)',
    'reports.windKwh': 'पवन ऊर्जा (kWh)',
    'reports.dieselKwh': 'डीजल बैकअप (kWh)',
    'reports.loadKwh': 'स्टेशन लोड मांग (kWh)',
    'settings.title': 'सिस्टम सेटिंग्स और सीमाएं',
    'settings.subtitle': 'ध्रुवीय स्टेशन टेलीमेट्री पैरामीटर, रिज़र्व सुरक्षा सीमाएं और एमएल मॉडल कॉन्फ़िगर करें।',
    'settings.configurable': 'कॉन्फ़िगर करने योग्य',
    'settings.saveBtn': 'सेटिंग्स सहेजें',
    'settings.saving': 'SQLITE में सहेजा जा रहा है...',
    'settings.saveSuccess': 'सिस्टम कॉन्फ़िगरेशन सफलतापूर्वक SQLite डेटाबेस में सहेजा गया।',
    'settings.langTitle': 'भाषा और क्षेत्रीय प्राथमिकताएं',
    'settings.langSubtitle': 'एप्लिकेशन इंटरफ़ेस भाषा चुनें। सभी नेविगेशन और रिपोर्ट्स तुरंत अपडेट होंगे।',
    'settings.stationTitle': 'स्टेशन पहचान और टेलीमेट्री नोड',
    'settings.stationName': 'ध्रुवीय स्टेशन का नाम',
    'settings.location': 'भौगोलिक निर्देशांक / स्थान',
    'settings.storageTitle': 'ऊर्जा भंडारण और जनरेटर सीमाएं',
    'settings.batteryMinReserve': 'बैटरी न्यूनतम सुरक्षित रिज़र्व (%)',
    'settings.batteryFloor': 'डिफ़ॉल्ट सुरक्षा सीमा: 30%',
    'settings.criticalLoadThreshold': 'क्रिटिकल लोड सर्ज सीमा (kW)',
    'settings.overloadTrigger': 'डिफ़ॉल्ट ओवरलोड ट्रिगर: 55 kW',
    'settings.dieselAutoStart': 'डीजल जनरेटर ऑटो-स्टार्ट',
    'settings.dieselDeficit': 'कमी बनी रहने पर डीजल प्रारंभ करता है',
    'settings.mlTitle': 'मशीन लर्निंग इंजन सेटिंग्स',
    'settings.forecastHorizon': 'पूर्वानुमान विंडो',
    'settings.modelAlgorithm': 'प्राथमिक एमएल रिग्रेसर आर्किटेक्चर',
    'settings.alertsTitle': 'अलर्ट सदस्यता और रूटिंग',
    'settings.criticalAlerts': 'क्रिटिकल ओवरलोड और विसंगति अलर्ट',
    'settings.criticalAlertsDesc': 'गंभीर घाटे पर तत्काल ऑपरेटर अलार्म ट्रिगर करें।',
    'settings.warningAlerts': 'अनुमानित कमी चेतावनी अलर्ट',
    'settings.warningAlertsDesc': '6 घंटे का उत्पादन बेसलाइन से नीचे जाने पर सूचित करें।',
    'settings.systemNotifications': 'सिस्टम टेलीमेट्री सूचनाएं',
    'settings.systemNotificationsDesc': 'आवधिक स्थिति रिपोर्ट और बैटरी चक्र अनुकूलन।',
  },

  ta: {
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.prediction': 'முன்கணிப்பு',
    'nav.optimization': 'உகப்பாக்கம்',
    'nav.alerts': 'எச்சரிக்கைகள் & முரண்பாடுகள்',
    'nav.simulation': 'சிமுலேஷன்',
    'nav.reports': 'அறிக்கைகள்',
    'nav.data': 'தரவு மேலாண்மை',
    'nav.settings': 'அமைப்புகள்',
    'nav.operators': 'இயக்குநர் மேலாண்மை',
    'nav.logout': 'வெளியேறு',
    'nav.health': 'கணினி நிலை',
    'nav.station': 'பாரதி நிலையம்',
    'nav.online': 'இணைப்பில் உள்ளது',
    'header.title': 'துருவ ஆற்றல் AI',
    'header.subtitle': 'தன்னாட்சி மைக்ரோகிரிட் கட்டுப்பாடு',
    'header.simulation': 'ஆர்க்டிக் மைக்ரோகிரிட் சிமுலேஷன்',
    'header.digitalTwin': 'தொலைநிலை ஆற்றல் அமைப்பு • நேரலை டிஜிட்டல் இரட்டை',
    'header.systemMode': 'கணினி பயன்முறை',
    'header.autonomous': 'தன்னாட்சி',
    'header.localTime': 'உள்ளூர் நேரம்',
    'header.admin': 'நிர்வாகி',
    'header.operator': 'இயக்குநர்',
    'header.active': 'செயலில்',
    'header.chooseLanguage': 'மொழி',
    'reports.title': 'ஆற்றல் பகுப்பாய்வு & சிமுலேஷன் அறிக்கைகள்',
    'reports.subtitle': 'வரலாற்று உற்பத்தி அளவீடுகள், உருவகப்படுத்துதல் முடிவுகள் மற்றும் எரிபொருள் பதிவுகள்',
    'reports.daily': 'தினசரி',
    'reports.weekly': 'வாராந்திர',
    'reports.monthly': 'மாதாந்திர',
    'reports.exportCsv': 'CSV ஏற்றுமதி',
    'reports.exporting': 'ஏற்றுமதியாகிறது...',
    'reports.totalRenewable': 'மொத்த புதுப்பிக்கத்தக்க உற்பத்தி',
    'reports.zeroCarbon': '100% பூஜ்ஜிய-கார்பன் ஆற்றல்',
    'reports.renewableFraction': 'புதுப்பிக்கத்தக்க பங்கு',
    'reports.target': 'இலக்கு: >90% புதுப்பிக்கத்தக்கது',
    'reports.dieselConserved': 'சேமிக்கப்பட்ட டீசல் எரிபொருள்',
    'reports.co2Saved': '~1.45 டன் CO2 உமிழ்வு குறைப்பு',
    'reports.resilienceScore': 'மீள்திறன் மதிப்பீடு',
    'reports.safeMargin': 'பாதுகாப்பான துருவ இயக்க வரம்பு',
    'reports.tableTitle': 'டிஜிட்டல் இரட்டை சிமுலேஷன் மற்றும் தணிக்கைப் பதிவு',
    'reports.liveRuns': 'நேரலை ஒத்திசைக்கப்பட்ட இயக்கங்கள்',
    'reports.colTime': 'செயல்படுத்தல் நேரம்',
    'reports.colRun': 'டெலிமெட்ரி இயக்கம்',
    'reports.colRenewable': 'புதுப்பிக்கத்தக்க பங்கு',
    'reports.colLoad': 'நிலைய சுமை',
    'reports.colDiesel': 'பயன்படுத்திய டீசல்',
    'reports.colStatus': 'நிலை',
    'reports.chartTitle': 'ஆற்றல் உற்பத்தி vs. நிலைய தேவை விவரம் (kWh)',
    'reports.chartSubtitle': 'உண்மையான தேவையுடன் அடுக்கப்பட்ட புதுப்பிக்கத்தக்க பங்களிப்பு (சூரிய + காற்று).',
    'reports.solarKwh': 'சூரிய ஆற்றல் (kWh)',
    'reports.windKwh': 'காற்று ஆற்றல் (kWh)',
    'reports.dieselKwh': 'டீசல் காப்பு (kWh)',
    'reports.loadKwh': 'நிலைய சுமை தேவை (kWh)',
    'settings.title': 'கணினி அமைப்புகள் & வரம்புகள்',
    'settings.subtitle': 'துருவ நிலைய டெலிமெட்ரி அளவுருக்கள், பாதுகாப்பு வரம்புகள் மற்றும் ML மாதிரிகளை அமைக்கவும்.',
    'settings.configurable': 'மாற்றமைக்கக்கூடியது',
    'settings.saveBtn': 'அமைப்புகளைச் சேமி',
    'settings.saving': 'SQLITE இல் சேமிக்கிறது...',
    'settings.saveSuccess': 'கணினி கட்டமைப்பு SQLite தரவுத்தளத்தில் வெற்றிகரமாகச் சேமிக்கப்பட்டது.',
    'settings.langTitle': 'மொழி & பிராந்திய விருப்பங்கள்',
    'settings.langSubtitle': 'பயன்பாட்டு இடைமுக மொழியைத் தேர்ந்தெடுக்கவும். உடனடியாக புதுப்பிக்கப்படும்.',
    'settings.stationTitle': 'நிலைய அடையாளம் & டெலிமெட்ரி முனை',
    'settings.stationName': 'துருவ நிலையத்தின் பெயர்',
    'settings.location': 'புவியியல் ஆயத்தொலைவுகள் / இருப்பிடம்',
    'settings.storageTitle': 'ஆற்றல் சேமிப்பு & ஜெனரேட்டர் வரம்புகள்',
    'settings.batteryMinReserve': 'பேட்டரி குறைந்தபட்ச சேமிப்பு (%)',
    'settings.batteryFloor': 'இயல்புநிலை பாதுகாப்பு வரம்பு: 30%',
    'settings.criticalLoadThreshold': 'முக்கிய சுமை உயர்வு வரம்பு (kW)',
    'settings.overloadTrigger': 'இயல்புநிலை அதிக சுமை வரம்பு: 55 kW',
    'settings.dieselAutoStart': 'டீசல் ஜெனரேட்டர் தானியங்கி இயக்கம்',
    'settings.dieselDeficit': 'பற்றாக்குறை நீடித்தால் டீசலை இயக்கும்',
    'settings.mlTitle': 'மெஷின் லேர்னிங் இயந்திர அமைப்புகள்',
    'settings.forecastHorizon': 'முன்கணிப்பு கால அளவு',
    'settings.modelAlgorithm': 'முதன்மை ML ரெக்ரஸர் கட்டமைப்பு',
    'settings.alertsTitle': 'எச்சரிக்கை சந்தாக்கள் & ரூட்டிங்',
    'settings.criticalAlerts': 'முக்கிய சுமை & முரண்பாட்டு எச்சரிக்கைகள்',
    'settings.criticalAlertsDesc': 'வெப்ப அதிகரிப்பு அல்லது பற்றாக்குறை ஏற்படும் போது எச்சரிக்கும்.',
    'settings.warningAlerts': 'முன்கணிக்கப்பட்ட பற்றாக்குறை எச்சரிக்கைகள்',
    'settings.warningAlertsDesc': '6 மணி நேர உற்பத்தி குறையும் போது தெரிவிக்கும்.',
    'settings.systemNotifications': 'கணினி டெலிமெட்ரி அறிவிப்புகள்',
    'settings.systemNotificationsDesc': 'அவ்வப்போது நிலை அறிக்கைகள் மற்றும் பேட்டரி உகப்பாக்கம்.',
  },

  ar: {
    'nav.dashboard': 'لوحة القيادة',
    'nav.prediction': 'التنبؤ بالأحمال',
    'nav.optimization': 'التحسين الذكي',
    'nav.alerts': 'التنبيهات والشذوذ',
    'nav.simulation': 'المحاكاة التوأم',
    'nav.reports': 'التقارير التحليلية',
    'nav.data': 'إدارة البيانات',
    'nav.settings': 'إعدادات النظام',
    'nav.operators': 'إدارة المشغلين',
    'nav.logout': 'تسجيل الخروج',
    'nav.health': 'سلامة النظام',
    'nav.station': 'محطة بهاراتي',
    'nav.online': 'متصل',
    'header.title': 'طاقة القطب AI',
    'header.subtitle': 'التحكم الذاتي في الشبكة الدقيقة',
    'header.simulation': 'محاكاة شبكة القطب الدقيقة',
    'header.digitalTwin': 'نظام الطاقة عن بُعد • توأم رقمي مباشر',
    'header.systemMode': 'وضع النظام',
    'header.autonomous': 'تلقائي بالكامل',
    'header.localTime': 'التوقيت المحلي',
    'header.admin': 'المسؤول',
    'header.operator': 'المشغل',
    'header.active': 'نشط',
    'header.chooseLanguage': 'اللغة',
    'reports.title': 'تحليلات الطاقة وتقارير المحاكاة',
    'reports.subtitle': 'مقاييس التوليد التاريخية ونتائج المحاكاة وسجلات تدقيق الوقود',
    'reports.daily': 'يومي',
    'reports.weekly': 'أسبوعي',
    'reports.monthly': 'شهري',
    'reports.exportCsv': 'تصدير CSV',
    'reports.exporting': 'جارٍ التصدير...',
    'reports.totalRenewable': 'إجمالي الطاقة المتجددة المولدة',
    'reports.zeroCarbon': '100% طاقة خالية من الكربون',
    'reports.renewableFraction': 'نسبة الطاقة المتجددة',
    'reports.target': 'الهدف: >90% متجددة',
    'reports.dieselConserved': 'وقود الديزل الموفر',
    'reports.co2Saved': 'توفير ما يعادل 1.45 طن من ثاني أكسيد الكربون',
    'reports.resilienceScore': 'مؤشر المرونة',
    'reports.safeMargin': 'هامش التشغيل الآمن بالقطب',
    'reports.tableTitle': 'سجل تشغيل المحاكاة والتدقيق للتوأم الرقمي',
    'reports.liveRuns': 'تشغيل متزامن مباشر',
    'reports.colTime': 'وقت التنفيذ',
    'reports.colRun': 'مهمة القياس عن بعد',
    'reports.colRenewable': 'حصة الطاقة المتجددة',
    'reports.colLoad': 'حمل المحطة',
    'reports.colDiesel': 'الديزل المستهلك',
    'reports.colStatus': 'الحالة',
    'reports.chartTitle': 'توليد الطاقة مقابل الطلب بالمحطة (كيلوواط ساعة)',
    'reports.chartSubtitle': 'مساهمة الطاقة المتجددة المجمعة (شمسية + رياح) مقارنة بالطلب الفعلي.',
    'reports.solarKwh': 'الطاقة الشمسية (kWh)',
    'reports.windKwh': 'طاقة الرياح (kWh)',
    'reports.dieselKwh': 'احتياطي الديزل (kWh)',
    'reports.loadKwh': 'طلب الحمل (kWh)',
    'settings.title': 'إعدادات النظام وعتبات الأمان',
    'settings.subtitle': 'تكوين معلمات المحطة القطبية وعتبات البطارية ونماذج التعلم الآلي.',
    'settings.configurable': 'قابل للتخصيص',
    'settings.saveBtn': 'حفظ الإعدادات',
    'settings.saving': 'جارٍ الحفظ في SQLITE...',
    'settings.saveSuccess': 'تم حفظ الإعدادات بنجاح في قاعدة بيانات SQLite.',
    'settings.langTitle': 'تفضيلات اللغة والمنطقة',
    'settings.langSubtitle': 'اختر لغة واجهة التطبيق. يتم التحديث فوراً لجميع الأقسام.',
    'settings.stationTitle': 'تعريف المحطة وعقدة القياس',
    'settings.stationName': 'اسم المحطة القطبية',
    'settings.location': 'الإحداثيات الجغرافية / الموقع',
    'settings.storageTitle': 'تخزين الطاقة وعتبات المولدات',
    'settings.batteryMinReserve': 'الحد الأدنى لاحتياطي البطارية (%)',
    'settings.batteryFloor': 'حد الأمان الافتراضي: 30%',
    'settings.criticalLoadThreshold': 'عتبة زيادة الحمل الحرجة (kW)',
    'settings.overloadTrigger': 'عتبة التحميل الزائد: 55 kW',
    'settings.dieselAutoStart': 'التشغيل التلقائي لمولد الديزل',
    'settings.dieselDeficit': 'تشغيل الديزل في حالة استمرار العجز',
    'settings.mlTitle': 'إعدادات محرك التعلم الآلي',
    'settings.forecastHorizon': 'أفق التنبؤ الزمني',
    'settings.modelAlgorithm': 'هيكل خوارزمية التنبؤ',
    'settings.alertsTitle': 'اشتراكات التنبيهات والتوجيه',
    'settings.criticalAlerts': 'تنبيهات الحمل الزائد والشذوذ',
    'settings.criticalAlertsDesc': 'إطلاق إنذار فوري عند حدوث زيادة حرارية أو عجز كبير.',
    'settings.warningAlerts': 'تنبيهات العجز المتوقع',
    'settings.warningAlertsDesc': 'الإخطار عند انخفاض التوليد المتوقع خلال 6 ساعات.',
    'settings.systemNotifications': 'إخطارات القياس عن بعد',
    'settings.systemNotificationsDesc': 'تقارير دورية وتحسين دورات البطارية.',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    try {
      const saved = localStorage.getItem('polar_language');
      if (saved && TRANSLATIONS[saved]) return saved;
    } catch (e) {}
    return 'en';
  });

  const setLanguage = (langCode) => {
    if (TRANSLATIONS[langCode]) {
      setLanguageState(langCode);
      try {
        localStorage.setItem('polar_language', langCode);
        document.documentElement.lang = langCode;
        if (langCode === 'ar') {
          document.documentElement.dir = 'rtl';
        } else {
          document.documentElement.dir = 'ltr';
        }
      } catch (e) {}
    }
  };

  useEffect(() => {
    document.documentElement.lang = language;
    if (language === 'ar') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
  }, [language]);

  const t = (key, fallback = '') => {
    const currentDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (currentDict[key]) return currentDict[key];
    if (TRANSLATIONS.en[key]) return TRANSLATIONS.en[key];
    return fallback || key;
  };

  const currentLangMeta = AVAILABLE_LANGUAGES.find((l) => l.code === language) || AVAILABLE_LANGUAGES[0];

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        currentLangMeta,
        availableLanguages: AVAILABLE_LANGUAGES,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;
